Repository fluentlabs-xyz/docs-docusaurus, pull requests merged in 2025-07, with the labels that each got.

#63 fix(config): Enforce dark theme for all CSS elements
  docusaurus.config.js
Labels: bug

#84 docs: update landing page
  docs/contribute.md
  docs/developer-preview/build-with-the-fluentbase-sdk.md
  docs/get-started.md
  docs/glossary.md
  docs/knowledge-base/blended-101.md
  docs/knowledge-base/fluent-overview.md
  docs/knowledge-base/the-fluent-l2-network.md
  docs/knowledge-base/the-fluent-vm.md
  docs/knowledge-base/the-fluentbase-framework.md
  docs/quickstart.md
  docs/resources.md
  docs/resources/_category_.json
  docs/resources/awesome-fluent.md
  docs/resources/tech-book.md
  src/css/custom.scss
  static/img/blended-app.png
  static/img/fluent-banner.png
  static/img/multivm-vs-blendedvm.png
  static/img/single-blended-exec.png
Labels: documentation

#81 docs: update network info
  docs/contribute.md
  docs/developer-preview/build-with-the-fluentbase-sdk.md
  docs/developer-preview/connect-to-fluent.md
  docs/get-started.md
  docs/glossary.md
  docs/knowledge-base/blended-101.md
  docs/knowledge-base/fluent-overview.md
  docs/knowledge-base/the-fluent-l2-network.md
  docs/knowledge-base/the-fluent-vm.md
  docs/knowledge-base/the-fluentbase-framework.md
  docs/quickstart.md
  docs/resources.md
  docs/resources/_category_.json
  docs/resources/awesome-fluent.md
  docs/resources/tech-book.md
  docusaurus.config.js
  package-lock.json
  src/css/custom.scss
  static/img/blended-app.png
  static/img/fluent-banner.png
  static/img/multivm-vs-blendedvm.png
  static/img/single-blended-exec.png
Labels: documentation, enhancement
